repository_type: pipeline

nf_core_version: 3.3.2

lint: {}

template:
  org: nf-core
  name: rnaseqpipelinetest
  description: A test pipeline for RNAseq
  author: Nicolai Oswald
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - gpu
  is_nfcore: true
