contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #rnaseqpipeline channel"
    url: https://nfcore.slack.com/channels/rnaseqpipeline
    about: Discussion about the nf-core/rnaseqpipeline pipeline
